version: '3.8'

name: films_test

services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: films-postgres-test
    ports:
      - 5432:5432
    env_file:
      - .env.test
      